from __future__ import annotations

from typing import Protocol


class Transport(Protocol):
    async def emit(self, event: dict) -> None: ...
    async def receive(self) -> dict | None: ...
    async def aclose(self) -> None: ...
